package com.tour.suse.entity;
import java.io.Serializable;
import java.util.Set;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : City.java
//  @ Date : 2014/5/22
//  @ Author : @\zhuxiao
/*
 * 景区所属城市
 * */
public class City implements Serializable{
	private Long id;
	private String name;
	private Set<Note> notes;
	private Set<Scenic> scenices;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	public Set<Note> getNotes() {
		return notes;
	}
	public void setNotes(Set<Note> notes) {
		this.notes = notes;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public Set<Scenic> getScenices() {
		return scenices;
	}
	public void setScenices(Set<Scenic> scenices) {
		this.scenices = scenices;
	}
	public City(){}
	public City(Long id){this.id=id;}
	public City(String name){
		this.name = name;
	}
}
