package com.tour.suse.entity;
import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.zip.DataFormatException;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Note.java
//  @ Date : 2014/5/22
//  @ Author : @\zhuxiao

@SuppressWarnings("serial")
public class Note implements Serializable{
	private Long id;
	private String title;
	private String imageUrl;
	private String content;
	private Date postTime;
	private String formatTime;
	private int goodNum;
	private int badNum;
	private int clickNum;
	private int commentNum;
	private Integer status=1;//回收站为0
	private String delUsername;
	private String username;
	private String cityname;
	private String authorimg;
	private Long authorId;
	private User author;
	private Set<NoteComment> noteComments;
	private Scenic scenic;
	
	//热门游记构造函数
	public Note(Long id, String title, Date postTime) {
		super();
		this.id = id;
		this.title = title.length()>14?title.substring(0,14)+"...":title;
		SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
		this.formatTime = sdf.format(postTime);
	}

	
	public Note(Long id, String title, String imageUrl, String content,
			Date postTime, int clickNum, int commentNum, String username,
			String cityname,String authorimg,Long authorId) {
		super();
		this.id = id;
		this.title = title.length()>14?title.substring(0,14)+"...":title;
		this.imageUrl = imageUrl;
		this.content = content;
		this.postTime = postTime;
		this.clickNum = clickNum;
		this.commentNum = commentNum;
		this.username = username;
		this.cityname = cityname;
		this.authorimg =authorimg;
		this.authorId= authorId;
	}


	public String getCityname() {
		return cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Note(Long id, String title, String imageUrl, Date postTime) {
		this.id = id;
		this.title = title.length()>14?title.substring(0,14)+"...":title;
		this.imageUrl = imageUrl;
		this.postTime = postTime;
	}
	
	public Note( String title, int goodNum, int badNum, int clickNum,
			int commentNum, String imageUrl, String content, Date postTime,
			Integer status, User author,
			Set<NoteComment> noteComments,Scenic s) {
		this.title = title.length()>14?title.substring(0,14)+"...":title;
		this.goodNum = goodNum;
		this.badNum = badNum;
		this.clickNum = clickNum;
		this.commentNum = commentNum;
		this.imageUrl = imageUrl;
		this.content = content;
		this.postTime = postTime;
		this.status = status;
		this.author = author;
		this.noteComments = noteComments;
		this.scenic = s;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	
	public int getGoodNum() {
		return goodNum;
	}
	public void setGoodNum(int goodNum) {
		this.goodNum = goodNum;
	}
	
	public int getBadNum() {
		return badNum;
	}
	public void setBadNum(int badNum) {
		this.badNum = badNum;
	}
	
	public String getImageUrl() {
		return imageUrl;
	}
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
	
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public Date getPostTime() {
		return postTime;
	}
	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}
	public int getClickNum() {
		return clickNum;
	}
	public void setClickNum(int clickNum) {
		this.clickNum = clickNum;
	}
	
	public int getCommentNum() {
		return commentNum;
	}
	public void setCommentNum(int commentNum) {
		this.commentNum = commentNum;
	}
	
	public User getAuthor() {
		return author;
	}
	public void setAuthor(User author) {
		this.author = author;
	}
	
	public Set<NoteComment> getNoteComments() {
		return noteComments;
	}
	public void setNoteComments(Set<NoteComment> noteComments) {
		this.noteComments = noteComments;
	}
	public Note(){}
	public Note(String name){
		this.title = title.length()>14?title.substring(0,14)+"...":title;
		this.postTime = new Date();
	}

	public Scenic getScenic() {
		return scenic;
	}

	public void setScenic(Scenic scenic) {
		this.scenic = scenic;
	}

	public String getAuthorimg() {
		return authorimg;
	}

	public void setAuthorimg(String authorimg) {
		this.authorimg = authorimg;
	}


	public String getFormatTime() {
		return formatTime;
	}


	public void setFormatTime(String formatTime) {
		this.formatTime = formatTime;
	}


	public String getDelUsername() {
		return delUsername;
	}


	public void setDelUsername(String delUsername) {
		this.delUsername = delUsername;
	}


	public Long getAuthorId() {
		return authorId;
	}


	public void setAuthorId(Long authorId) {
		this.authorId = authorId;
	}
}
