package com.tour.suse.entity;
import java.io.Serializable;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ScenicClass.java
//  @ Date : 2014/5/22
//  @ Author : @\zhuxiao
public class ScenicClass implements Serializable{
	private Long id;
	private String name;
	private Set< ScenicClass> children;
	private ScenicClass parent;
	private Set<Scenic> scenices;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public Set<ScenicClass> getChildren() {
//		children
//		for(int i=0;i<children.l
//		)
		return children;
	}
	public void setChildren(Set<ScenicClass> children) {
		
		this.children = children;
	}
	public ScenicClass getParent() {
		return parent;
	}
	public void setParent(ScenicClass parent) {
		this.parent = parent;
	}
	
    public Set<Scenic> getScenices() {
		return scenices;
	}
	public void setScenices(Set<Scenic> scenices) {
		this.scenices = scenices;
	}
	public ScenicClass(String name) {
		this.name = name;
	}
	public ScenicClass(String name,ScenicClass parent) {
		this.name = name;
		this.parent = parent;
	}
	public ScenicClass(){}
	public ScenicClass(Long id){this.id=id;}
}
