package com.tour.suse.entity;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import com.tour.suse.util.HtmlUtil;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Scenic.java
//  @ Date : 2014/5/22
//  @ Author : @\zhuxiao
public class Scenic implements Serializable{
	private Long id;
	private String name;
	private String level;
	private String  description;
	private String imageUrl ;
	private String scenicLine;
	private Date postTime;
	private User author;
	private City city;
	private Set<Note> notes=new HashSet<Note>();
	private Set<ScenicComment> scenicComments;
	private Set<ScenicClass> scenicClasses;
	private Integer status=1;
	private Float environmentScore=0.0f;
	private Float transportScore=0.0f;
	private Integer clickNum=0;
	private Integer commentNum=0;
	private Integer realCommentNum=0;
	private Integer goodCount=0;
	private Integer badCount=0;
	private Float serviceScore=0.0f;
	private Float peopleScore=0.0f;
	private Float totalScore=0.0f;
	
	//不作为表的属性
	private String username;
	private String cityname;
	private Integer notenum;
	public Scenic(){}
	
	//评论ajax返回景区分数
	public Scenic(Long id, Float environmentScore, Float transportScore,
			Integer commentNum, Float serviceScore, Float peopleScore,
			Float totalScore) {
		super();
		this.id = id;
		this.environmentScore = environmentScore;
		this.transportScore = transportScore;
		this.commentNum = commentNum;
		this.serviceScore = serviceScore;
		this.peopleScore = peopleScore;
		this.totalScore = totalScore;
	}
	
	//推荐景区构造函数
	public Scenic(Long id, String name, String imageUrl) {
		this.id = id;
		this.name = name;
		this.imageUrl = imageUrl.split(";")[0];//截取第一个图片地址
	}
	

	public Scenic(String name, String level, String description, Date postTime,
			Integer clickNum, Integer commentNum, String username,
			String cityname) {
		this.name = name;
		this.level = level;
		
		String con = HtmlUtil.ConvertToText(description);
		if(con.length()<20)
		{con = con.substring(0, con.length());}
		else{con = con.substring(0, 20);}
		this.description = con;
		this.postTime = postTime;
		this.clickNum = clickNum;
		this.commentNum = commentNum;
		this.username = username;
		this.cityname = cityname;
	}

	
	public Scenic(String name){
		this.name=name;
	}
	public Scenic(String name, String description, Integer clickNum) {
		super();
		this.name = name;
		this.description = description;
		this.clickNum = clickNum;
	}

	public Scenic(String name, String level, String description,
			String imageUrl, String scenicLine, Date postTime, User author,
			City city, Set<ScenicComment> scenicComments,
			Set<ScenicClass> scenicClasses, Integer status,
			Float environmentScore, Float transportScore, Integer clickNum,
			Integer commentNum, Integer realCommentNum, Integer goodCount,
			Integer badCount, Float serviceScore, Float peopleScore,
			Float totalScore) {
		super();
		this.name = name;
		this.level = level;
		this.description = description;
		this.imageUrl = imageUrl;
		this.scenicLine = scenicLine;
		this.postTime = postTime;
		this.author = author;
		this.city = city;
		this.scenicComments = scenicComments;
		this.scenicClasses = scenicClasses;
		this.status = status;
		this.environmentScore = environmentScore;
		this.transportScore = transportScore;
		this.clickNum = clickNum;
		this.commentNum = commentNum;
		this.realCommentNum = realCommentNum;
		this.goodCount = goodCount;
		this.badCount = badCount;
		this.serviceScore = serviceScore;
		this.peopleScore = peopleScore;
		this.totalScore = totalScore;
	}
	
	public Scenic(String name, String level, String description,
			String imageUrl, String scenicLine, Date postTime, User author,
			City city, Set<ScenicClass> scenicClasses) {
		super();
		this.name = name;
		this.level = level;
		this.description = description;
		this.imageUrl = imageUrl;
		this.scenicLine = scenicLine;
		this.postTime = postTime;
		this.author = author;
		this.city = city;
		this.scenicClasses = scenicClasses;
	}
	
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public Integer getRealCommentNum() {
		return realCommentNum;
	}
	public void setRealCommentNum(Integer realCommentNum) {
		this.realCommentNum = realCommentNum;
	}

	
	public Set<ScenicComment> getScenicComments() {
		return scenicComments;
	}
	public void setScenicComments(Set<ScenicComment> scenicComments) {
		this.scenicComments = scenicComments;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	
	public String getImageUrl() {
		return imageUrl;
	}
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public City getCity() {
		return city;
	}
	public void setCity(City city) {
		this.city = city;
	}
	
	public String getLevel() {
		return level;
	}
	public void setLevel(String level) {
		this.level = level;
	}
	
	

	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Integer getClickNum() {
		return clickNum;
	}
	public void setClickNum(Integer clickNum) {
		this.clickNum = clickNum;
	}
	
	public User getAuthor() {
		return author;
	}
	public void setAuthor(User author) {
		this.author = author;
	}
	
	public Integer getCommentNum() {
		return commentNum;
	}
	
	public void setCommentNum(Integer commentNum) {
		this.commentNum = commentNum;
	}
	
	public Integer getGoodCount() {
		return goodCount;
	}
	public void setGoodCount(Integer goodCount) {
		this.goodCount = goodCount;
	}
	
	public Integer getBadCount() {
		return badCount;
	}
	public void setBadCount(Integer badCount) {
		this.badCount = badCount;
	}
	public Set<ScenicClass> getScenicClasses() {
		return scenicClasses;
	}
	public void setScenicClasses(Set<ScenicClass> scenicClasses) {
		this.scenicClasses = scenicClasses;
	}
	public Date getPostTime() {
		return postTime;
	}
	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}
	
	public String getScenicLine() {
		return scenicLine;
	}
	public void setScenicLine(String scenicLine) {
		this.scenicLine = scenicLine;
	}
	public Float getEnvironmentScore() {
		return environmentScore;
	}
	public void setEnvironmentScore(Float environmentScore) {
		this.environmentScore = environmentScore;
	}
	public Float getTransportScore() {
		return transportScore;
	}
	public void setTransportScore(Float transportScore) {
		this.transportScore = transportScore;
	}
	public Float getServiceScore() {
		return serviceScore;
	}
	public void setServiceScore(Float serviceScore) {
		this.serviceScore = serviceScore;
	}
	public Float getPeopleScore() {
		return peopleScore;
	}
	public void setPeopleScore(Float peopleScore) {
		this.peopleScore = peopleScore;
	}
	public Float getTotalScore() {
		return totalScore;
	}
	public void setTotalScore(Float totalScore) {
		this.totalScore = totalScore;
	}
	public Set<Note> getNotes() {
		return notes;
	}
	public void setNotes(Set<Note> notes) {
		this.notes = notes;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCityname() {
		return cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	public Integer getNotenum() {
		return notenum;
	}

	public void setNotenum(Integer notenum) {
		this.notenum = notenum;
	}
}
